/* tslint:disable */
/* eslint-disable */
/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ContactMessage } from '../models';
// @ts-ignore
import { HTTPValidationError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ContactApi - axios parameter creator
 * @export
 */
export const ContactApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Post Contact
         * @param {ContactMessage} contactMessage 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewContact: async (contactMessage: ContactMessage, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactMessage' is not null or undefined
            assertParamExists('createNewContact', 'contactMessage', contactMessage)
            const localVarPath = `/contact`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: contactMessage,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/contact',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(contactMessage, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContactApi - functional programming interface
 * @export
 */
export const ContactApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContactApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Post Contact
         * @param {ContactApiCreateNewContactRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewContact(requestParameters: ContactApiCreateNewContactRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const contactMessage: ContactMessage = {
                customer_email: requestParameters.customer_email,
                content: requestParameters.content
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNewContact(contactMessage, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ContactApi - factory interface
 * @export
 */
export const ContactApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContactApiFp(configuration)
    return {
        /**
         * 
         * @summary Post Contact
         * @param {ContactApiCreateNewContactRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewContact(requestParameters: ContactApiCreateNewContactRequest, options?: AxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.createNewContact(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createNewContact operation in ContactApi.
 * @export
 * @interface ContactApiCreateNewContactRequest
 */
export type ContactApiCreateNewContactRequest = {
    
} & ContactMessage

/**
 * ContactApiGenerated - object-oriented interface
 * @export
 * @class ContactApiGenerated
 * @extends {BaseAPI}
 */
export class ContactApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Post Contact
     * @param {ContactApiCreateNewContactRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiGenerated
     */
    public createNewContact(requestParameters: ContactApiCreateNewContactRequest, options?: AxiosRequestConfig) {
        return ContactApiFp(this.configuration).createNewContact(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
