/* tslint:disable */
/* eslint-disable */
/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { OnboardingStates } from '../models';
// @ts-ignore
import { OnboardingStatesNullable } from '../models';
// @ts-ignore
import { OnboardingUpdatableProperties } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * OnboardingApi - axios parameter creator
 * @export
 */
export const OnboardingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get user onboarding information for the current user
         * @summary Get User Onboarding Handler
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfo: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/onboarding`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/onboarding',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update user onboarding information for the current user
         * @summary Update User Onboarding Handler
         * @param {OnboardingUpdatableProperties} onboardingUpdatableProperties 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserOnboarding: async (onboardingUpdatableProperties: OnboardingUpdatableProperties, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'onboardingUpdatableProperties' is not null or undefined
            assertParamExists('updateUserOnboarding', 'onboardingUpdatableProperties', onboardingUpdatableProperties)
            const localVarPath = `/onboarding`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AuthBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: onboardingUpdatableProperties,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/onboarding',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(onboardingUpdatableProperties, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OnboardingApi - functional programming interface
 * @export
 */
export const OnboardingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OnboardingApiAxiosParamCreator(configuration)
    return {
        /**
         * Get user onboarding information for the current user
         * @summary Get User Onboarding Handler
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInfo(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OnboardingStatesNullable>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserInfo(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Update user onboarding information for the current user
         * @summary Update User Onboarding Handler
         * @param {OnboardingApiUpdateUserOnboardingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserOnboarding(requestParameters: OnboardingApiUpdateUserOnboardingRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OnboardingStates>> {
            const onboardingUpdatableProperties: OnboardingUpdatableProperties = {
                onboarding_a: requestParameters.onboarding_a,
                onboarding_b1: requestParameters.onboarding_b1,
                onboarding_b2: requestParameters.onboarding_b2,
                onboarding_b3: requestParameters.onboarding_b3
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserOnboarding(onboardingUpdatableProperties, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * OnboardingApi - factory interface
 * @export
 */
export const OnboardingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OnboardingApiFp(configuration)
    return {
        /**
         * Get user onboarding information for the current user
         * @summary Get User Onboarding Handler
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfo(options?: AxiosRequestConfig): AxiosPromise<OnboardingStatesNullable> {
            return localVarFp.getUserInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * Update user onboarding information for the current user
         * @summary Update User Onboarding Handler
         * @param {OnboardingApiUpdateUserOnboardingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserOnboarding(requestParameters: OnboardingApiUpdateUserOnboardingRequest, options?: AxiosRequestConfig): AxiosPromise<OnboardingStates> {
            return localVarFp.updateUserOnboarding(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for updateUserOnboarding operation in OnboardingApi.
 * @export
 * @interface OnboardingApiUpdateUserOnboardingRequest
 */
export type OnboardingApiUpdateUserOnboardingRequest = {
    
} & OnboardingUpdatableProperties

/**
 * OnboardingApiGenerated - object-oriented interface
 * @export
 * @class OnboardingApiGenerated
 * @extends {BaseAPI}
 */
export class OnboardingApiGenerated extends BaseAPI {
    /**
     * Get user onboarding information for the current user
     * @summary Get User Onboarding Handler
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnboardingApiGenerated
     */
    public getUserInfo(options?: AxiosRequestConfig) {
        return OnboardingApiFp(this.configuration).getUserInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update user onboarding information for the current user
     * @summary Update User Onboarding Handler
     * @param {OnboardingApiUpdateUserOnboardingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OnboardingApiGenerated
     */
    public updateUserOnboarding(requestParameters: OnboardingApiUpdateUserOnboardingRequest, options?: AxiosRequestConfig) {
        return OnboardingApiFp(this.configuration).updateUserOnboarding(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
