/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiBrainDefinitionSecret
 */
export interface ApiBrainDefinitionSecret {
    /**
     * 
     * @type {string}
     * @memberof ApiBrainDefinitionSecret
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiBrainDefinitionSecret
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiBrainDefinitionSecret
     */
    'type': string;
}

