/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiBrainDefinitionSchemaProperty } from './api-brain-definition-schema-property';

/**
 * 
 * @export
 * @interface ApiBrainDefinitionSchemaNullable
 */
export interface ApiBrainDefinitionSchemaNullable {
    /**
     * 
     * @type {Array<ApiBrainDefinitionSchemaProperty>}
     * @memberof ApiBrainDefinitionSchemaNullable
     */
    'properties'?: Array<ApiBrainDefinitionSchemaProperty>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiBrainDefinitionSchemaNullable
     */
    'required'?: Array<string>;
}

