/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKeyInfo
 */
export interface ApiKeyInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiKeyInfo
     */
    'key_id': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyInfo
     */
    'creation_time': string;
}

