/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiBrainAllowedMethods } from './api-brain-allowed-methods';
import { ApiBrainDefinitionSchema } from './api-brain-definition-schema';
import { ApiBrainDefinitionSecret } from './api-brain-definition-secret';

/**
 * 
 * @export
 * @interface ApiBrainDefinitionEntityInput
 */
export interface ApiBrainDefinitionEntityInput {
    /**
     * 
     * @type {string}
     * @memberof ApiBrainDefinitionEntityInput
     */
    'brain_id': string;
    /**
     * 
     * @type {ApiBrainAllowedMethods}
     * @memberof ApiBrainDefinitionEntityInput
     */
    'method': ApiBrainAllowedMethods;
    /**
     * 
     * @type {string}
     * @memberof ApiBrainDefinitionEntityInput
     */
    'url': string;
    /**
     * 
     * @type {ApiBrainDefinitionSchema}
     * @memberof ApiBrainDefinitionEntityInput
     */
    'params': ApiBrainDefinitionSchema;
    /**
     * 
     * @type {ApiBrainDefinitionSchema}
     * @memberof ApiBrainDefinitionEntityInput
     */
    'search_params': ApiBrainDefinitionSchema;
    /**
     * 
     * @type {Array<ApiBrainDefinitionSecret>}
     * @memberof ApiBrainDefinitionEntityInput
     */
    'secrets': Array<ApiBrainDefinitionSecret>;
    /**
     * 
     * @type {boolean}
     * @memberof ApiBrainDefinitionEntityInput
     */
    'raw'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiBrainDefinitionEntityInput
     */
    'jq_instructions'?: string | null;
}

