/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKey
 */
export interface ApiKey {
    /**
     * 
     * @type {string}
     * @memberof ApiKey
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKey
     */
    'key_id': string;
    /**
     * 
     * @type {number}
     * @memberof ApiKey
     */
    'days': number;
    /**
     * 
     * @type {boolean}
     * @memberof ApiKey
     */
    'only_chat': boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiKey
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKey
     */
    'creation_time': string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiKey
     */
    'is_active': boolean;
}

