/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiBrainDefinitionSchemaProperty
 */
export interface ApiBrainDefinitionSchemaProperty {
    /**
     * 
     * @type {string}
     * @memberof ApiBrainDefinitionSchemaProperty
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof ApiBrainDefinitionSchemaProperty
     */
    'type': string;
    /**
     * 
     * @type {Array<any>}
     * @memberof ApiBrainDefinitionSchemaProperty
     */
    'enum'?: Array<any> | null;
    /**
     * 
     * @type {string}
     * @memberof ApiBrainDefinitionSchemaProperty
     */
    'name': string;
}

