/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GetChatHistoryOutput } from './get-chat-history-output';
import { MessageIdProperty } from './message-id-property';
import { Notification } from './notification';
import { NotificationsStatusEnum } from './notifications-status-enum';

/**
 * @type BodyProperty
 * @export
 */
export type BodyProperty = GetChatHistoryOutput | Notification;


