/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BrainSubscriptionUpdatableProperties
 */
export interface BrainSubscriptionUpdatableProperties {
    /**
     * 
     * @type {string}
     * @memberof BrainSubscriptionUpdatableProperties
     */
    'rights'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrainSubscriptionUpdatableProperties
     */
    'email': string;
}

