/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiBrainDefinitionEntityInputNullable } from './api-brain-definition-entity-input-nullable';
import { BrainIntegrationUpdateSettingsNullable } from './brain-integration-update-settings-nullable';

/**
 * 
 * @export
 * @interface BrainUpdatableProperties
 */
export interface BrainUpdatableProperties {
    /**
     * 
     * @type {string}
     * @memberof BrainUpdatableProperties
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrainUpdatableProperties
     */
    'name'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BrainUpdatableProperties
     */
    'temperature'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BrainUpdatableProperties
     */
    'model'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BrainUpdatableProperties
     */
    'max_tokens'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BrainUpdatableProperties
     */
    'status'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrainUpdatableProperties
     */
    'prompt_id'?: string | null;
    /**
     * 
     * @type {ApiBrainDefinitionEntityInputNullable}
     * @memberof BrainUpdatableProperties
     */
    'brain_definition'?: ApiBrainDefinitionEntityInputNullable | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrainUpdatableProperties
     */
    'connected_brains_ids'?: Array<string> | null;
    /**
     * 
     * @type {BrainIntegrationUpdateSettingsNullable}
     * @memberof BrainUpdatableProperties
     */
    'integration'?: BrainIntegrationUpdateSettingsNullable | null;
}

