/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BrainIntegrationSettings
 */
export interface BrainIntegrationSettings {
    /**
     * 
     * @type {string}
     * @memberof BrainIntegrationSettings
     */
    'integration_id': string;
    /**
     * 
     * @type {object}
     * @memberof BrainIntegrationSettings
     */
    'settings': object;
}

