/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BodyProperty } from './body-property';
import { ChatItemType } from './chat-item-type';

/**
 * 
 * @export
 * @interface ChatItem
 */
export interface ChatItem {
    /**
     * 
     * @type {ChatItemType}
     * @memberof ChatItem
     */
    'item_type': ChatItemType;
    /**
     * 
     * @type {BodyProperty}
     * @memberof ChatItem
     */
    'body': BodyProperty;
}

