/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Chat
 */
export interface Chat {
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'chat_id': string;
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'creation_time': string;
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'chat_name': string;
}

