/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ChatQuestion
 */
export interface ChatQuestion {
    /**
     * 
     * @type {string}
     * @memberof ChatQuestion
     */
    'question': string;
    /**
     * 
     * @type {string}
     * @memberof ChatQuestion
     */
    'model'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChatQuestion
     */
    'temperature'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChatQuestion
     */
    'max_tokens'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ChatQuestion
     */
    'brain_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatQuestion
     */
    'prompt_id'?: string | null;
}

