/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CrawlWebsite
 */
export interface CrawlWebsite {
    /**
     * 
     * @type {string}
     * @memberof CrawlWebsite
     */
    'url': string;
    /**
     * 
     * @type {boolean}
     * @memberof CrawlWebsite
     */
    'js'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CrawlWebsite
     */
    'depth'?: number;
    /**
     * 
     * @type {number}
     * @memberof CrawlWebsite
     */
    'max_pages'?: number;
    /**
     * 
     * @type {number}
     * @memberof CrawlWebsite
     */
    'max_time'?: number;
}

