/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiBrainAllowedMethods } from './api-brain-allowed-methods';
import { ApiBrainDefinitionSchema } from './api-brain-definition-schema';
import { ApiBrainDefinitionSchemaNullable } from './api-brain-definition-schema-nullable';
import { ApiBrainDefinitionSecret } from './api-brain-definition-secret';

/**
 * 
 * @export
 * @interface CreateApiBrainDefinitionNullable
 */
export interface CreateApiBrainDefinitionNullable {
    /**
     * 
     * @type {ApiBrainAllowedMethods}
     * @memberof CreateApiBrainDefinitionNullable
     */
    'method': ApiBrainAllowedMethods;
    /**
     * 
     * @type {string}
     * @memberof CreateApiBrainDefinitionNullable
     */
    'url': string;
    /**
     * 
     * @type {ApiBrainDefinitionSchemaNullable}
     * @memberof CreateApiBrainDefinitionNullable
     */
    'params'?: ApiBrainDefinitionSchemaNullable | null;
    /**
     * 
     * @type {ApiBrainDefinitionSchema}
     * @memberof CreateApiBrainDefinitionNullable
     */
    'search_params'?: ApiBrainDefinitionSchema;
    /**
     * 
     * @type {Array<ApiBrainDefinitionSecret>}
     * @memberof CreateApiBrainDefinitionNullable
     */
    'secrets'?: Array<ApiBrainDefinitionSecret> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateApiBrainDefinitionNullable
     */
    'raw'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CreateApiBrainDefinitionNullable
     */
    'jq_instructions'?: string | null;
}

