/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BrainIntegrationSettingsNullable } from './brain-integration-settings-nullable';
import { BrainTypeNullable } from './brain-type-nullable';
import { CreateApiBrainDefinitionNullable } from './create-api-brain-definition-nullable';

/**
 * 
 * @export
 * @interface CreateBrainProperties
 */
export interface CreateBrainProperties {
    /**
     * 
     * @type {string}
     * @memberof CreateBrainProperties
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrainProperties
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBrainProperties
     */
    'status'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBrainProperties
     */
    'model'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateBrainProperties
     */
    'temperature'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateBrainProperties
     */
    'max_tokens'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBrainProperties
     */
    'prompt_id'?: string | null;
    /**
     * 
     * @type {BrainTypeNullable}
     * @memberof CreateBrainProperties
     */
    'brain_type'?: BrainTypeNullable | null;
    /**
     * 
     * @type {CreateApiBrainDefinitionNullable}
     * @memberof CreateBrainProperties
     */
    'brain_definition'?: CreateApiBrainDefinitionNullable | null;
    /**
     * 
     * @type {object}
     * @memberof CreateBrainProperties
     */
    'brain_secrets_values'?: object | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateBrainProperties
     */
    'connected_brains_ids'?: Array<string> | null;
    /**
     * 
     * @type {BrainIntegrationSettingsNullable}
     * @memberof CreateBrainProperties
     */
    'integration'?: BrainIntegrationSettingsNullable | null;
}

