/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PromptStatusEnum } from './prompt-status-enum';

/**
 * Properties that can be received on prompt creation
 * @export
 * @interface CreatePromptProperties
 */
export interface CreatePromptProperties {
    /**
     * 
     * @type {string}
     * @memberof CreatePromptProperties
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePromptProperties
     */
    'content': string;
    /**
     * 
     * @type {PromptStatusEnum}
     * @memberof CreatePromptProperties
     */
    'status'?: PromptStatusEnum;
}

