/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NotificationsStatusEnum } from './notifications-status-enum';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'datetime': string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'chat_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'message'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'action': string;
    /**
     * 
     * @type {NotificationsStatusEnum}
     * @memberof Notification
     */
    'status': NotificationsStatusEnum;
}

