/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Properties that can be received on onboarding update
 * @export
 * @interface OnboardingUpdatableProperties
 */
export interface OnboardingUpdatableProperties {
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingUpdatableProperties
     */
    'onboarding_a'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingUpdatableProperties
     */
    'onboarding_b1'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingUpdatableProperties
     */
    'onboarding_b2'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingUpdatableProperties
     */
    'onboarding_b3'?: boolean | null;
}

