/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Response when getting onboarding
 * @export
 * @interface OnboardingStates
 */
export interface OnboardingStates {
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingStates
     */
    'onboarding_a': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingStates
     */
    'onboarding_b1': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingStates
     */
    'onboarding_b2': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingStates
     */
    'onboarding_b3': boolean;
}

