/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PromptStatusEnum } from './prompt-status-enum';

/**
 * 
 * @export
 * @interface Prompt
 */
export interface Prompt {
    /**
     * 
     * @type {string}
     * @memberof Prompt
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Prompt
     */
    'content': string;
    /**
     * 
     * @type {PromptStatusEnum}
     * @memberof Prompt
     */
    'status'?: PromptStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Prompt
     */
    'id': string;
}

