/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PromptStatusEnumNullable } from './prompt-status-enum-nullable';

/**
 * Properties that can be received on prompt update
 * @export
 * @interface PromptUpdatableProperties
 */
export interface PromptUpdatableProperties {
    /**
     * 
     * @type {string}
     * @memberof PromptUpdatableProperties
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PromptUpdatableProperties
     */
    'content'?: string | null;
    /**
     * 
     * @type {PromptStatusEnumNullable}
     * @memberof PromptUpdatableProperties
     */
    'status'?: PromptStatusEnumNullable | null;
}

