/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiBrainDefinitionEntityOutputNullable } from './api-brain-definition-entity-output-nullable';
import { BrainType } from './brain-type';

/**
 * 
 * @export
 * @interface PublicBrain
 */
export interface PublicBrain {
    /**
     * 
     * @type {string}
     * @memberof PublicBrain
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicBrain
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PublicBrain
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof PublicBrain
     */
    'number_of_subscribers'?: number;
    /**
     * 
     * @type {string}
     * @memberof PublicBrain
     */
    'last_update': string;
    /**
     * 
     * @type {BrainType}
     * @memberof PublicBrain
     */
    'brain_type': BrainType;
    /**
     * 
     * @type {ApiBrainDefinitionEntityOutputNullable}
     * @memberof PublicBrain
     */
    'brain_definition'?: ApiBrainDefinitionEntityOutputNullable | null;
}

