/*
FastAPI

Open-source RAG Framework

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface QuestionAndAnswer
 */
export interface QuestionAndAnswer {
    /**
     * 
     * @type {string}
     * @memberof QuestionAndAnswer
     */
    'question': string;
    /**
     * 
     * @type {string}
     * @memberof QuestionAndAnswer
     */
    'answer': string;
}

